%% Example: public QES plume plotting
% This example contains no site-specific building, monitoring-point,
% nuclear-facility, or coordinate data.
%
% Before running:
%   1. Generate QES-Winds and QES-Plume NetCDF outputs.
%   2. Set the two file paths below to the public test-case outputs.
%   3. Ensure readNetCDF.m and plot_qes_plume_public.m are on the MATLAB path.

clear;
clc;
close all;

% Example relative paths. Replace the file basenames with the outputs
% generated by the public QES test case being used.
windsFile = "../QES-data/example_windsOut.nc";
plumeFile = "../QES-data/example_plumeOut.nc";

% Vertical concentration layer to plot.
plotLayer = 1;

% Terrain contours can be enabled for public/non-restricted test cases.
drawTerrain = true;

plot_qes_plume_public( ...
    windsFile, ...
    plumeFile, ...
    plotLayer, ...
    drawTerrain);
